Repository Pulsar312/Produce-Pong, pull requests merged in 2022-05, with the labels that each got.

#40 recipes -> dict method
  food/Recipe.py
Labels: enhancement

#42 Quick additions to make sure achievements is getting sent each request on profile
  app.py
  avatar.py
Labels: enhancement

#25 Direct messages and sticky footer
  app.py
  food/chef.py
  message.py
  pong/PongGame.py
  static/functions.js
  static/style.css
  templates/base.html
  templates/div_templates/about.html
  templates/div_templates/homepage.html
  templates/index.html
  templates/notification_template/notification.html
Labels: enhancement

#48 Finish food artwork and design of the pages
  static/pong.css
  static/recipes/avocado_toast.png
  static/recipes/banana_bread.png
  static/recipes/berry_muffin.png
  static/recipes/breakfast_hash.png
  static/recipes/curry.png
  static/recipes/french_fries.png
  static/recipes/french_onion_soup.png
  static/recipes/fried_rice.png
  static/recipes/fruit_smoothie.png
  static/recipes/nicholas_special_mac_and_cheese.png
  static/recipes/pancake.png
  static/recipes/pizza.png
  static/recipes/pot_roast.png
  static/recipes/potato_soup.png
  static/recipes/ramen.png
  static/recipes/salad.png
  static/recipes/sandwich.png
  static/recipes/shepherds_pie.png
  static/recipes/spicy_ramen.png
  static/recipes/steak_and_mashed_potato.png
  static/recipes/stuffed_potato.png
  static/styleHomepageSignedOut.css
  templates/pong_templates/historic_game.html
Labels: enhancement

#50 Fix some minor errors
  app.py
  database.py
  static/functions.js
Labels: bug

#52 Cleaner ingredRandom() implementation and reorganize winner's page
  static/pong.css
  static/profilePage.css
  templates/pong_templates/historic_game.html
Labels: enhancement

#55 Fix page scrolling with key presses in pong game
  static/pong.js
Labels: bug

#56 Fix invite button and keyboard shortcuts in the game
  static/pong.js
  templates/div_templates/message.html
Labels: bug

#57 Add some final touches
  static/profilePage.css
  static/style.css
  templates/div_templates/homepage.html
  templates/div_templates/homepage_templates/homepage-signed-in.html
  templates/div_templates/homepage_templates/homepage-signed-out.html
  templates/div_templates/message.html
  templates/div_templates/profile.html
Labels: enhancement

#61 Profile Buttons CSS :)
  static/profilePage.css
  templates/div_templates/profile.html
Labels: enhancement

#62 Advertisement gif, rearrange about page order, fix text align for right score on game page, footer links to another tab
  static/advertisement.gif
  static/advertisement.png
  static/pong.css
  templates/base.html
  templates/div_templates/contact.html
  templates/div_templates/homepage.html
Labels: enhancement

#63 Automatic WS protocol detection, remove testing endpoint, improve front-end efficiency
  app.py
  static/pong.js
  templates/pong_templates/game.html
Labels: enhancement

#64 object-fit: contain for PFP
  static/profilePage.css
Labels: bug

#66 Clean up idle games, add custom error page
  app.py
  authentication.py
  error.py
  pong/PongGame.py
  pong/pong_views.py
  pong/pongapi.py
  static/pong.css
  static/pong.js
  static/style.css
  templates/error.html
  templates/pong_templates/game.html
  templates/pong_templates/games.html
Labels: enhancement

#67 Add Docker volumes
  docker-compose.yml
Labels: enhancement

#68 Fix text visibility and remove a print
  authentication.py
  templates/div_templates/login.html
Labels: enhancement

#69 Fix login error message style
  static/style.css
  templates/div_templates/login.html
Labels: enhancement

#70 Update README.md
  README.md
Labels: documentation, enhancement
